// File generated by FlutterFire configuration helper.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for Goodwin Wholesale across all supported platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7mSehg_4cOvPl3-751B8md-D5Nyzy84',
    appId: '1:442430046114:web:ccfdaa84fdc86e53483cfb',
    messagingSenderId: '442430046114',
    projectId: 'goodwin-c861d',
    authDomain: 'goodwin-c861d.firebaseapp.com',
    storageBucket: 'goodwin-c861d.firebasestorage.app',
    measurementId: 'G-1MWFXQEL0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCef85yM08P9YSPpEZsTVkdFmMhg6wLEPE',
    appId: '1:442430046114:android:f38b04717942c4e6483cfb',
    messagingSenderId: '442430046114',
    projectId: 'goodwin-c861d',
    storageBucket: 'goodwin-c861d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQgQkRaqCCfr7GCTbqSVvZDc0YsZHdFys',
    appId: '1:442430046114:ios:aa591bb90e243dea483cfb',
    messagingSenderId: '442430046114',
    projectId: 'goodwin-c861d',
    storageBucket: 'goodwin-c861d.firebasestorage.app',
    iosBundleId: 'com.example.goodwin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQgQkRaqCCfr7GCTbqSVvZDc0YsZHdFys',
    appId: '1:442430046114:ios:aa591bb90e243dea483cfb',
    messagingSenderId: '442430046114',
    projectId: 'goodwin-c861d',
    storageBucket: 'goodwin-c861d.firebasestorage.app',
    iosBundleId: 'com.example.goodwin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg7mSehg_4cOvPl3-751B8md-D5Nyzy84',
    appId: '1:442430046114:web:ccfdaa84fdc86e53483cfb',
    messagingSenderId: '442430046114',
    projectId: 'goodwin-c861d',
    authDomain: 'goodwin-c861d.firebaseapp.com',
    storageBucket: 'goodwin-c861d.firebasestorage.app',
    measurementId: 'G-1MWFXQEL0L',
  );
}

